// Generated by CoffeeScript 1.7.1
(function() {
  var app, bodyParser, express, playSong, port, router, spotify;

  express = require("express");

  spotify = require("spotify-node-applescript");

  bodyParser = require("body-parser");

  app = express();

  app.set("views", __dirname + "/views");

  app.set("view engine", "html");

  app.engine("html", require("hbs").__express);

  app.use(bodyParser());

  app.use("/public", express["static"](__dirname + "/public"));

  router = express.Router();

  playSong = function(uri) {
    spotify.playTrack(uri, function() {});
  };

  router.get("/play/:uri", function(req, res) {
    playSong(req.params.uri);
    res.render("redirect");
  });

  router.post("/play", function(req, res) {
    playSong(req.body.uri);
    res.render("redirect");
  });

  router.post("/", function(req, res) {
    playSong(req.body.uri);
    res.render("redirect");
  });

  router.get("/", function(req, res) {
    res.render("search");
  });

  app.use("/", router);

  port = 3000;

  app.listen(port);

  console.log("Magic happens on port " + port);

}).call(this);
